name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout kode dari repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Python environment
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3️⃣ Cek environment variable (optional)
      - name: Check Env
        run: |
          echo "Dataset path: $CSV_URL"

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      # 5️⃣ Jalankan MLflow Project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      # 6️⃣ Simpan hasil run (mlruns) ke repo GitHub
      - name: Save mlruns to repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

          git add mlruns/ || echo "No mlruns to add"
          git commit -m "Save mlruns from CI run" || echo "No changes to commit"

          # Gunakan token untuk push agar tidak gagal otorisasi
          git push https://x-access-token:${GH_TOKEN}@github.com/Hamzah1302/Latihan-CI.git main
