name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout kode dari repo
      - uses: actions/checkout@v3

      # 2Ô∏è‚É£ Setup Python environment
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3Ô∏è‚É£ Cek environment variable (optional)
      - name: Check Env
        run: |
          echo "Dataset path: $CSV_URL"

      # 4Ô∏è‚É£ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn pandas numpy

      # 5Ô∏è‚É£ Jalankan MLflow Project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local


      # üß© Tambahkan langkah ini untuk mengaktifkan Git LFS
      - name: Set up Git LFS
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git lfs install
          git lfs track "mlruns/**"
          git add .gitattributes
          git commit -m "Track large files in mlruns with Git LFS" || true
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Hamzah1302/Latihan-CI.git main

      # 6Ô∏è‚É£ Simpan hasil run (mlruns) ke repo GitHub
      - name: Save mlruns to repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"

          git add mlruns/ || echo "No changes"
          git commit -m "Save mlruns from CI run" || echo "Nothing to commit"

          git push https://x-access-token:${GH_TOKEN}@github.com/Hamzah1302/Latihan-CI.git main

